version: "3.3"
services:
  auto-youtube-dl:
    image: tons/auto-youtube-dl
    build: .
    volumes:
      - ./Downloads:/Downloads
    command: "https://www.youtube.com/playlist?list=PLNiDb1qWsHSG2RpAZPrikxXL3G98eyohH"
    environment:
      DOWNLOAD_DIRECTORY: /Downloads
